modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/BrewingCoder/BrewBlocks/issues"

[[mods]]
modId="brewblocks"
version="${file.jarVersion}"
 displayName="Brewer's Extra Blocks: Slime, Clay, Decorative, String crops, etc."

# A URL to query for updates for this mod. See the JSON update specification <here>
# updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/BrewingCoder/BrewBlocks"
credits="I'm a total noob, thanks to all the modders that have open source mods"
authors="BrewingCoder (BrewDrinkCode, Brewer)" #optional
description='''
 Useful World Gen:
    Clay Block veins
    Sticky Ore (Slime dropping Ore)
    Flax crops (Spawns in plains, drops seeds/strings)

 Decorative Blocks:
    Basalt (Deep dark higher resolution basalt (similar to Railcraft's)
    Quarried Stone (Clean White higher resolution (again, Loved those old RC blocks, and cheaper than quartz)
'''


[[dependencies.brewblocks]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.brewblock]]
    modId="brewteamlib"
    mandatory=true
    versionRange="[1.0.3+]"
    ordering="NONE"
    side="BOTH"
